#!name=高德地图去广告

#!desc=高德地图去广告

#!source=https://yfamily.vercel.app

#!icon=https://github.com/dotSpecs/shadowrocket-modules/raw/main/icons/AmapAds.png

[Script]

高德地图去广告=type=http-response,script-path=^https?:\/\/.*\.amap\.com\/ws\/faas\/amap-navigation\/main-page,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/amap.js

高德地图去广告1=type=http-response,script-path=^https?:\/\/.*\.amap\.com\/ws\/valueadded\/alimama\/splash_screen,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/amap.js

高德地图去广告2=type=http-response,script-path=^https?:\/\/.*\.amap\.com\/ws\/msgbox\/pull,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/amap.js

高德地图去广告3=type=http-response,script-path=^https?:\/\/.*\.amap\.com\/ws\/shield\/dsp\/profile\/index\/nodefaas,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/amap.js

高德地图去广告4=type=http-response,script-path=^https?:\/\/.*\.amap\.com\/ws\/shield\/search\/new_hotword,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/amap.js





[URL Rewrite]

^https?:\/\/.*\.amap\.com\/ws\/boss\/order_web\/\w{8}_information _ reject-200

^https?:\/\/.*\.amap\.com\/ws\/asa\/ads_attribution _ reject

^https?:\/\/.*\.amap\.com\/ws\/shield\/scene\/recommend _ reject-dict

^https?:\/\/.*\.amap\.com\/uploadimg\/\w+\.gif _ reject-img

^https?:\/\/.*\.amap\.com\/ws\/valueadded\/weather _ reject-dict



[MITM]

hostname= %APPEND% *amap.com
