#!name=百度产品去广告

#!desc=百度产品去广告


[URL Rewrite]

^https?:\/\/mime\.baidu\.com\/v\d\/IosStart\/getStartInfo reject
^https?:\/\/mime\.baidu\.com\/v\d\/activity\/advertisement reject

^https?:\/\/appwk\.baidu\.com\/xpage\/interface\/wknaad reject

# 百度网盘
^https?:\/\/pan\.baidu\.com\/act\/v\d\/(bchannel|welfare)\/list reject
^https?:\/\/pan\.baidu\.com\/rest\/2\.0\/pcs\/ad reject
^https?:\/\/pan\.baidu\.com\/act\/api\/activityentry reject

# 百度地图
^https?:\/\/newclient\.map\.baidu\.com\/client\/phpui.*qt=rgc reject-200
^https?:\/\/newclient\.map\.baidu\.com\/client\/phpui.*qt=hw reject-200
^https?:\/\/newclient\.map\.baidu\.com\/client\/phpui2\/\?qt=ads reject-200
^https?:\/\/newclient\.map\.baidu\.com\/client\/crossmarketing reject-200
^https?:\/\/newclient\.map\.baidu\.com\/client\/usersystem\/home\/dynamic reject-200

^https:\/\/mbd\.baidu\.com\/newspage\/api\/getmobads\?page\=landingshare reject

^https?:\/\/httpdns\.baidubce\.com reject-200


[Script]

baidumap=type=http-response,pattern=^https:\/\/newclient\.map\.baidu\.com\/client\/phpui2\/\?qt=ads,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/baidumap.js


[MITM] 

hostname = %APPEND% pan.baidu.com,httpdns.baidubce.com,newclient.map.baidu.com,mbd.baidu.com,afd.baidu.com,appwk.baidu.com,

