#!name=酷我音乐
#!desc=完美解锁酷我音乐

# 待验证

[MITM]
hostname = %APPEND% *.kuwo.cn, *.lrts.me

[Script]
酷我音乐 = type=http-response,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/kuwo.js,pattern=^https?:\/\/.*\.(kuwo|lrts)\.(cn|me)\/(a\.p|music\.pay|(vip\/(v2|enc)\/(theme|user\/vip))|(EcomResource|(Mobile)?Ad)Serv(er|ice)).*,max-size=131072,requires-body=true,timeout=10,script-update-interval=0,enable=true