#!name=喜马拉雅去广告

#!desc=喜马拉雅去广告

#!icon=https://github.com/dotSpecs/shadowrocket-modules/raw/main/icons/xmlyad.png


[MITM]

hostname= %APPEND% adse.wsa.ximalaya.com
#hostname= %APPEND% *.xima*.*,*.xmcdn.*,*.ximalaya.com

[URL Rewrite]

# ～ XiMaLaYa_喜马拉雅_播放页_Live@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/mobile-playpage\/view\/ - reject
#^https?:\/\/.*\.ximalaya\.com\/mobile-playpage\/view\/ - reject

# ～ XiMaLaYa_喜马拉雅_MyInfo红点提醒@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/chaos-notice-web\/v1\/message\/preview\/list - reject
#^https?:\/\/.*\.ximalaya\.com\/chaos-notice-web\/v1\/message\/preview\/list - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽大红包Tips@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/social-web\/bottomTabs\/dynamicEntrance\/status - reject
#^https?:\/\/.*\.ximalaya\.com\/social-web\/bottomTabs\/dynamicEntrance\/status - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽gif弹窗Ad@ddgksf2013

#^https?:\/\/.*\.xmcdn\.com\/\w{8}\/\w{4}-\w{16}\/.+gif$ - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽Aged请求@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/(dog-portal\/checkOld|(child-mobile\/child|aged-mobile\/aged)\/mode\/query) - reject
#^https?:\/\/.*\.ximalaya\.com\/(dog-portal\/checkOld|(child-mobile\/child|aged-mobile\/aged)\/mode\/query) - reject

# ～ XiMaLaYa_喜马拉雅_部分Tab弹窗@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/discovery-feed\/isShowUserGiftPendant - reject
#^https?:\/\/.*\.ximalaya\.com\/discovery-feed\/isShowUserGiftPendant - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽红点提示@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/mobile-user\/unread - reject
#^https?:\/\/.*\.ximalaya\.com\/mobile-user\/unread - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽minor请求@ddgksf2013

#^https?:\/\/.*\.xima.*\.com/mobile-user/minorProtection/pop - reject
#^https?:\/\/.*\.ximalaya\.com/mobile-user/minorProtection/pop - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽隐私搜集@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/collector\/xl\/v\d - reject
#^https?:\/\/.*\.ximalaya\.com\/collector\/xl\/v\d - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽版本更新@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/butler-portal\/versionCheck - reject
#^https?:\/\/.*\.ximalaya\.com\/butler-portal\/versionCheck - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽开屏广告@ddgksf2013

#^https?:\/\/(adse\.wsa|adse|adbehavior|xdcs-collector)\.xima.*\.com\/.* - reject
^https?:\/\/(adse\.wsa|adse|adbehavior|xdcs-collector)\.ximalaya\.com\/.* - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽位置请求@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/mobile\/discovery\/v\d\/location - reject
#^https?:\/\/.*\.ximalaya\.com\/mobile\/discovery\/v\d\/location - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽热搜词@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/hotWord - reject
#^https?:\/\/.*\.ximalaya\.com\/hotWord - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽搜索框定时_Ad@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/guideWord - reject
#^https?:\/\/.*\.ximalaya\.com\/guideWord - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽实时Ad请求@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/api\/v\d\/adRealTime - reject
#^https?:\/\/.*\.ximalaya\.com\/api\/v\d\/adRealTime - reject

# ～ XiMaLaYa_喜马拉雅_屏蔽ting_Ad@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/ting\/(loading|feed|home)? - reject
^https?:\/\/.*\.ximalaya\.com\/ting\/(loading|feed|home)? - reject

# ～ XiMaLaYa_喜马拉雅_修复轮播Ad失效Bug@ddgksf2013

#^https?:\/\/.*\.xima.*\.com\/discovery-feed\/focus\/queryF - reject
#^https?:\/\/.*\.ximalaya\.com\/discovery-feed\/focus\/queryF - reject

[Script]

# ～ XiMaLaYa_喜马拉雅_屏蔽首页滚动_Ad@ddgksf2013

#喜马拉雅去广告0=type=http-response,pattern=^https?:\/\/.*\.xima.*\.com\/discovery-feed\/v\d\/mix,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/xmly_json.js
#喜马拉雅去广告0-1=type=http-response,pattern=^https?:\/\/.*\.ximalaya\.com\/discovery-feed\/v\d\/mix,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/xmly_json.js

# ～ XiMaLaYa_喜马拉雅_屏蔽Tab页滚动_Ad@ddgksf2013

#喜马拉雅去广告1=type=http-response,pattern=^https?:\/\/.*\.xima.*\.com\/discovery-category\/v\d/category,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/xmly_json.js
#喜马拉雅去广告1-1=type=http-response,pattern=^https?:\/\/.*\.ximalaya\.com\/discovery-category\/v\d/category,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/xmly_json.js

# ～ XiMaLaYa_喜马拉雅_去除我的页面Ad_Tag@ddgksf2013

#喜马拉雅去广告2=type=http-response,pattern=^https?:\/\/.*\.xima.*\.com\/mobile-user\/v\d\/homePage,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/xmly_json.js
#喜马拉雅去广告2-1=type=http-response,pattern=^https?:\/\/.*\.ximalaya\.com\/mobile-user\/v\d\/homePage,requires-body=1,script-path=https://github.com/dotSpecs/shadowrocket-modules/raw/main/js/xmly_json.js

